version: '3.1'

services:
  postgres:
    image: postgres
    container_name: local_positiveteam_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: positiveteam_db
    volumes:
      - /d/work/docker/volumes/postgress:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    container_name: local_pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@dev.ru
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - /d/work/docker/volumes/pgadmin:/var/lib/pgadmin
    ports:
      - 81:80
    links:
      - "postgres:local-postgres-ip"