# Default project settings
server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 1024
  servlet:
    context-path: /positiveteam

spring:
  application:
    name: positiveteam-telegram-bot
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/root-changelog.xml
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: postgres
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    default-property-inclusion: non_null
